reviews:
  request_changes: true
  review_status: true

checks:
  spec_alignment:
    enabled: true
    guidance: |
      Verify changes align with specs/_meta.md, specs/functional.md, specs/technical.md,
      and research/specs/. Flag deviations and missing updates to specs.
  security:
    enabled: true
    guidance: |
      Look for secrets, insecure defaults, and missing validation. Ensure no direct API calls
      bypass MCP. Highlight any token exposure or unsafe file handling.

instructions: |
  Enforce spec-driven development. If code changes without spec updates, request changes.
  Require evidence of tests or explain missing tests.
